[package]
name = "hexyg-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hexyg"
path = "src/main.rs"

[dependencies]
hexyg-core = { path = "../hexyg-core" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
